Fail gracefully if RAW_VALUE does not contain a simple integer.
The RAW_VALUE column in the output of smartctl can contain values that
are not valid integers, leading to errors like the following:

  "Raw": int(fields[9])
  ValueError: invalid literal for int() with base 10: '0/0'

This commit replaces such values with None instead of crashing.

Fixes #2.